### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by vlee-harmonicinc** [eric-yhy/teamform-seed#104]
@RonaldShum 
Can you make a personal profile page for searching other user? 
Such as http://localhost:8080/profile.html?q=N1wjlh3AslWmAl0PVdfwKGJh1gV2 for showing user information of user with userid N1wjlh3AslWmAl0PVdfwKGJh1gV2

**Comment by RonaldShum** [comment]
Sure, but it's better to create a new profile.html for read only

**Comment by RonaldShum** [comment]
others profile can be view directly by profile.html?q=userid
