### ISSUE TITLE
Coding : User-friendly front-end interface

### ISSUE THREAD

**Issue by ccinin** [eric-yhy/teamform-seed#13]
Improve the front-end design to make our websites easy-to-use and give users a professional impression.

It can be done by improving the appearance using bootstrap and css and adding some interactive features such as dialog, drag and drop and alert box.

**Comment by vlee-harmonicinc** [comment]
Should we give warning rather than window.alert?
For example, if we enter invalid input, the input box became red?

**Comment by eric-yhy** [comment]
Sure. It is better but we should also accept window.alert when we cannot spend time on it.
