### ISSUE TITLE
Is repeated team/event/user name allowed?

### ISSUE THREAD

**Issue by vlee-harmonicinc** [eric-yhy/teamform-seed#21]
since we gonna use team/event/user id as key and name can be modified, name can be equal. But should we allowed same name?

**Comment by eric-yhy** [comment]
When a new team is created, the team name should not be allowed to be the same with others so that the name conflict can be resolved.

**Comment by vlee-harmonicinc** [comment]
@eric-yhy 
Actually, there are no more name conflict if we used event/ team id. Technically, it is able to have equal event/ team name.
