### ISSUE TITLE
Create Team: Admin @Eric

### ISSUE THREAD

**Issue by vlee-harmonicinc** [eric-yhy/teamform-seed#44]
When admin create team, event id became undefined.
From the description of Peter demo, admin don't need to create team.
It may be leaded to bug if the user's role is admin when being team leader. 
Should we just forbid admin create team? 
@eric-yhy

**Comment by eric-yhy** [comment]
If any users including students can be an admin, they also need to join a team. We can let admin be the super class of leader and admin can control everything that belongs to leader role.

**Comment by vlee-harmonicinc** [comment]
@eric-yhy
??? Admin and leader is role in firebase with different app and different controller, they are not object, we cannot make it into super class.
But then we have to include team action in the admin page and copy all javascript of leader to admin. Also, the layout will be confusing.
We didn't distingish user account as students or professor/ teachers, so the cases "any users including students can be an admin" is not exist. Unless you want change the user profile and enforce user to chose a role as student/ professor as we discuss before starting coding the project.

**Comment by eric-yhy** [comment]
Thanks. You are right and I changed for it.
