### ISSUE TITLE
Cannot fix alignment in admin.html

### ISSUE THREAD

**Issue by christietse** [eric-yhy/teamform-seed#48]
I cannot align the Edit Event and Announcements into the middle of the screen.
I tried CSS but seems something is overriding my code.

`      <div id="admin_page_controller">`
`         <div class="row">`
`            <div class="col-md-8 col-xs-8 text-left panel" ng-show="editable">`
`            more code here... `
`            </div>`
`         </div>`
`       </div>`

**Comment by vlee-harmonicinc** [comment]
@christietse 
I guess it may be because its class is "col-md-8 col-xs-8 text-left panel". May be you can try to wrap the whole class with other container.
How did you align it?

**Comment by christietse** [comment]
fixed this morning thanks
