### ISSUE TITLE
Bug: Cannot display deadline when it is before today

### ISSUE THREAD

**Issue by christietse** [eric-yhy/teamform-seed#52]
Bug in Admin.html
@htleeab @RonaldShum Can you please check the AngularJS?
Deadlines which are in the future is okay, but in the past is not able to display.

deadline at line 97

**Comment by RonaldShum** [comment]
It should be $scope.param.deadline for deadline from firebase
$scope.deadline is for editing team data.

**Comment by vlee-harmonicinc** [comment]
Yes, Ronald is right.
It is because the date picker of angular only accept date object but firebase cannot save date object.
scope.deadline is date.
scope.param.deadline is string.
