### ISSUE TITLE
Index: $ in url of member.html

### ISSUE THREAD

**Issue by vlee-harmonicinc** [eric-yhy/teamform-seed#94]
}else if (teamList.$getRecord(eventid).role == "member"){
				//the user is the one of the members of a team of the event
					var url = "member.html?eventid=" + eventid + "$teamid=" + teamList.$getRecord(eventid).teamid;
    				window.location.href = url;
					return true;

I'm doing accept invite of null user and read the url of index and found this. Since member.html is not finished, I'm not sure is it standard or typo.
@keungbryan

**Comment by keungbryan** [comment]
Sorry, I don't know what is going on since "$teamid=" + teamList.$getRecord(eventid).teamid; is not added by me
